---
- name: Install MySQL server
  sudo: yes
  apt:  pkg=mysql-server state=latest


- name: Add root user from anywhere to MySQL
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"

- name: Create MySQL database wordpress
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS wordpress;"
